### ISSUE TITLE
Moodle 3.0 - class="section-item current r0" not correctly matching to section diplayed

### ISSUE THREAD

**Issue by zuricx1** [mudrd8mz/moodle-block_course_contents#15]
I have problem where the class="section-item current r0" is simply not displaying correctly. When I click on different sections of the course in the block where I have placed on the right slide on my Moodle page the section is displayed correctly but the class="section-item current r0" is not correctly displaying the right section displayed on the paged it is stuck on the same section.

**Comment by mudrd8mz** [comment]
Can you provide a screenshot illustrating the issue and let me know the version of your Moodle, the version of the plugin and the theme you use?

**Comment by zuricx1** [comment]
Thank you for replying. 
The Moodle version is 3.0.1 build 20151221.The Theme is the default theme however I have tried others with the same result.You can see from the image that I am using 1 section per page option and that the current selection is number 2 however number 4 is highlighted as the current selection. It doesn't move from that selection even if I delete or change the course content.
Thank you
              
Date: Wed, 13 Jan 2016 10:11:11 -0800

**Comment by mudrd8mz** [comment]
Sorry, I can't see the image. Can you try to attach it via the Github web interface?

**Comment by zuricx1** [comment]
![untitled](https://cloud.githubusercontent.com/assets/16674758/12307188/a14457dc-ba35-11e5-99fb-f2c00426d7c6.jpg)

**Comment by zuricx1** [comment]
Although maybe not quite suitable in this section. I also wondered how easy or if it is possible to have the block not show 0 the general section in the list. Appreciate this is a rather personal request.

**Comment by mudrd8mz** [comment]
The leading zero not displayed any more - fixed in version 4.0 09b4d907fa4

Looking at the other issue now.

**Comment by mudrd8mz** [comment]
I am sorry. I am not able to replicate any buggy behaviour. if I create a course like you, showing once section on one page, and I click the "General" link in the block, I am correctyl returned to the main page of the course, with all sections displayed as collapsed (i.e. titles only).

This is expected behaviour.
