### ISSUE TITLE
Global preferences for adding the section numbering

### ISSUE THREAD

**Issue by abias** [mudrd8mz/moodle-block_course_contents#16]
Hi David,

we're happy to use this block from you from the next lecture term on. It's slick and does it's job well :)

There's only one thing: The numbering of sections is configurable within the block instance, but it is switched on by default. As an admin, I would be happy to have a global settings page where I could a) change this default or b) even better be able to disable this option at all. 

Do you think you can add a global preference page with this functionality?

Thanks,
Alex

**Comment by abias** [comment]
Hi David,

I saw that you added labels to this ticket, but did not give me an answer ;)

Do you have time to add this preference page or would you welcome a pull request?

Thanks,
Alex

**Comment by mudrd8mz** [comment]
Oh sorry. Of course, I never say no to a well crafted pull request. Your contributions will be welcome :-)

+1 to have a global setting to set the default.

I am not quite sure about disabling enumeration globally. Do you really believe that would be a useful setting? And if so, should there also be a way to force enumeration on? I learnt that when it comes to Moodle settings, the less options if often better.

**Comment by abias** [comment]
> Oh sorry. Of course, I never say no to a well crafted pull request. Your contributions will be welcome :-)

Great :)

> I am not quite sure about disabling enumeration globally. Do you really believe that would be a useful setting? And if so, should there also be a way to force enumeration on? I learnt that when it comes to Moodle settings, the less options if often better.

Well, there are users who fiddle with every setting just because it's there and regardless if it makes sense or not. I agree with you that less options are often better, but only for users and not for admins. I would prefer having an additional admin option which can be used to remove a user option ;)

Don't you think this could be boiled down to a setting with 4 options:
* Always add enumeration
* Never add enumeration
* Let the user decide in the block instance and enable enumeration by default
* Let the user decide in the block instance and don't enable enumeration by default

**Comment by mudrd8mz** [comment]
Yes, +1 for these options. Can I consider this as assigned to you?

**Comment by abias** [comment]
Hi David,

thanks for your positive feedback.

I won't do it myself, but I will ask our Moodle partner to submit a patch.

**Comment by comete-upo** [comment]
Hi everyone,

I just saw this issue after launching a pull request that allows to set default settings for the blocks, but not override the user's choices. See if you like it: #19 

Cheers.

**Comment by mudrd8mz** [comment]
Thanks everyone for your suggested patches. I believe I distilled the best from all proposals and this will be available in the next version of the block.

**Comment by mudrd8mz** [comment]
![image](https://cloud.githubusercontent.com/assets/85831/17230764/625e320c-551e-11e6-9a05-945018b48d19.png)
