### ISSUE TITLE
When on Section 0, course page link is also highlighted as well as section 0

### ISSUE THREAD

**Issue by 5882wolverine** [mudrd8mz/moodle-block_course_contents#24]
Following the recent merged changes for enumerating section 0 (thanks for reviewing and merging!) and further updates by yourself, when clicking on section 0, both section 0 and the original course page text above it are highlighted.  The course page text is also not a link as expected.  Please see below screenshots:

Current screenshot of merged changes that were further updated:
![course contents section 0 screenshot merged changes](https://user-images.githubusercontent.com/29977212/35618640-79d12cfc-0673-11e8-9b7e-d43e05467ddf.PNG)

Screenshot of how it looked before updated, merged changes:

![course contents section 0 screenshot original changes](https://user-images.githubusercontent.com/29977212/35618641-79e5c536-0673-11e8-9ae9-812205c78ec4.PNG)

I can fix this and submit another pull request.

**Comment by mudrd8mz** [comment]
I see. I haven't run into that case while testing as default course formats do not normally use the `?section=0` param. I agree it needs to be fixed.

However, conditions like ` if ( ($selected != 0) && (empty($selected)) )` or `if ( (!isset($selected)) && (empty($selected)) )` make it unnecessary harder to read. Why not simply

```
diff --git a/block_course_contents.php b/block_course_contents.php
index eec884e553..2683fe3f0a 100644
--- a/block_course_contents.php
+++ b/block_course_contents.php
@@ -189,7 +189,7 @@ class block_course_contents extends block_base {
             if (($i == 0) && ($displaycourselink)) {
                 $sectionclass = 'section-item';

-                if (empty($selected)) {
+                if ($selected === null) {
                     $sectionclass .= ' selected';
                 }
                 $text .= html_writer::start_tag('li', array('class' => $sectionclass));
@@ -203,7 +203,7 @@ class block_course_contents extends block_base {
                     $anchortext = $course->shortname;
                 }

-                if (empty($selected)) {
+                if ($selected === null) {
                     $text .= ' '.$anchortext;
                 } else {
                     $text .= ' '.html_writer::link(course_get_url($course), $anchortext);

```
