### ISSUE TITLE
Remove lib/simple_html_dom.php

### ISSUE THREAD

**Issue by tmuras** [mudrd8mz/moodle-block_course_contents#28]
Hello,

It looks like external library simple_html_dom.php is used only in one place:

`    
private function extract_title($summary)
`

I think we don't really need it - and can use PHP's functions. What do you think about removing this dependency?
The library seems dated and it's not fully functional - ie this won't load HTTPS:

```
    function __construct($str=null) {
        if ($str) {
            if (preg_match("/^http:\/\//i",$str) || is_file($str)) 
                $this->load_file($str); 
            else
                $this->load($str);
        }
    }
```

But it's not a problem here as it' used in your code.

**Comment by mudrd8mz** [comment]
Yes, +1 to remove the dependency ideally.

**Comment by mudrd8mz** [comment]
The version 6.0.0 will ship without this dependency. Thanks.
